const fs=require('fs');const crypto=require('crypto');const CDP=require('chrome-remote-interface');
const raw='results/pine-scenarios/s03-partial-exit/';
const expectedHash='eb174c78d3374a7cc13a6d2d82f2d1d51e9b0cc1e14ae3d7c12a8ddf394b2251';
const sha=s=>crypto.createHash('sha256').update(s.replace(/\r\n/g,'\n')).digest('hex');
(async()=>{
 const reopened=JSON.parse(fs.readFileSync(raw+'085-s02-reopened-get.json')).json.source;
 const saved=JSON.parse(fs.readFileSync(raw+'053-restore-s02-save.json')).json;
 const c=await CDP({host:'127.0.0.1',port:9222,target:'7980FA5955C48DD48FF5EDBF9615BD45'});
 const {result,exceptionDetails}=await c.Runtime.evaluate({expression:`(()=>{const chart=window.TradingViewApi._activeChartWidgetWV.value();const s=chart._chartWidget.model().model().dataSources().find(s=>s.id()==='XvcQgK');const inputs=chart.getStudyById('XvcQgK').getInputValues();return {url:location.href,symbol:chart.symbol(),resolution:chart.resolution(),chartType:chart.chartType(),studies:chart.getAllStudies(),statusType:s.status().type,statusError:s.status().errorDescription?.error||null,inputs:inputs.filter(i=>i.id!=='text')};})()`,returnByValue:true});
 await c.close();
 const state=result.value;
 const before=JSON.parse(JSON.parse(fs.readFileSync('results/pine-scenarios/s02-session-dashboard/raw/101-probe-study-status.json')).stdout);
 const previous=JSON.parse(before.result);
 const comparisons={hash:sha(reopened)===expectedHash,savedOriginalId:saved.script_id==='USER;6b325663a8a24b548558d60895ec3bc8',versionIncreased:saved.version==='8.0',sameStudies:JSON.stringify(state.studies.map(s=>s.id+':'+s.name))===JSON.stringify(previous.studies),sameStudyVersion:state.inputs.find(i=>i.id==='pineVersion').value===previous.pineVersion,sameStudyId:state.inputs.find(i=>i.id==='pineId').value===previous.pineId,sameKeep:state.inputs.find(i=>i.id==='in_4').value===previous.keep,sameStatus:state.statusType===previous.statusType&&state.statusError===previous.statusError,chartUnchanged:state.symbol==='BINANCE:ETHUSDT'&&state.resolution==='15'&&state.chartType===1};
 const report={expectedHash,reopenedHash:sha(reopened),saved,reopen:JSON.parse(fs.readFileSync(raw+'084-s02-restore-reopen.json')).json,originalSavedVersion:'5.0',newSavedVersion:'8.0',originalStudy:previous,currentStudy:state,comparisons,exceptionDetails};
 report.acceptanceRequired=['hash','savedOriginalId','versionIncreased','sameStudies','sameStudyId','sameKeep','sameStatus','chartUnchanged'];
 report.expectedStudyVersionChange={before:previous.pineVersion,after:state.inputs.find(i=>i.id==='pineVersion').value,explained:'Saving source in another editor updated the document version used by the existing chart study. Source was restored exactly; the version history cannot be undone.'};
 report.restoredStudyVersionMatchesSaved=state.inputs.find(i=>i.id==='pineVersion').value===saved.version;
 fs.writeFileSync(raw+'s02-restoration-verification.json',JSON.stringify(report,null,2));
 console.log(JSON.stringify({hash:report.reopenedHash,comparisons,savedVersion:saved.version,studyVersion:state.inputs.find(i=>i.id==='pineVersion').value}));
 if(exceptionDetails||report.acceptanceRequired.some(k=>comparisons[k]!==true)||!report.restoredStudyVersionMatchesSaved)throw Error('S02 restoration assertion failed');
})();
