const fs = require('fs');
const cp = require('child_process');
const path = require('path');
const out = path.resolve('results/pine-scenarios/s03-partial-exit');
fs.mkdirSync(out, {recursive:true});
const [tag, ...args] = process.argv.slice(2);
const target = '890408E3FA96D8076A7D49A8B3AF200A';
const cliArgs = ['src/cli/index.js','--target',target,...args];
if(fs.existsSync(path.join(out,tag+'.json')))throw Error('Refusing to overwrite existing evidence tag: '+tag);
if(args[0]==='indicator'&&args[1]==='set'&&args[2]!=='IC4e6I')throw Error('Mutating study fence mismatch');
if(args[0]==='pine'&&args[1]==='new')throw Error('New-document workflow is disabled after final saved identity has been fenced');
const mainId='USER;d90436c7ff524821b19882294c3c4548';
const s02Id='USER;6b325663a8a24b548558d60895ec3bc8';
const preId=['085-s02-reopened-get','086-reopen-own-main','116-switch-s02-get','117-switch-main-open'].includes(tag)?s02Id:mainId;
const postId=['084-s02-restore-reopen','115-switch-s02-open'].includes(tag)?s02Id:['086-reopen-own-main','117-switch-main-open'].includes(tag)?mainId:preId;
const checkFence=(suffix,id)=>{
 const f=cp.spawnSync(process.execPath,['qa/pine/scenarios/s03-partial-exit/fence.mjs',tag+suffix,id],{encoding:'utf8',timeout:10000});
 if(f.status!==0)throw Error('FENCE FAILED: '+f.stderr);
};
checkFence('-pre',preId);
const start = new Date();
const r = cp.spawnSync(process.execPath, cliArgs, {encoding:'utf8',timeout:65000,maxBuffer:8*1024*1024});
let json; try {json=JSON.parse(r.stdout);} catch {}
const record = {tag,command:['node',...cliArgs],started:start.toISOString(),duration_ms:Date.now()-start,status:r.status,signal:r.signal,error:r.error?.message,stdout:r.stdout,stderr:r.stderr,json};
fs.writeFileSync(path.join(out,tag+'.json'),JSON.stringify(record,null,2));
fs.appendFileSync(path.join(out,'commands.jsonl'),JSON.stringify(record)+'\n');
const safe = JSON.parse(JSON.stringify(json??r.stdout, (k,v)=>k==='rows'&&Array.isArray(v)?{length:v.length,first:v[0],last:v.at(-1)}:k==='source'&&typeof v==='string'&&v.includes('\n')?{chars:v.length}:k==='scripts'&&Array.isArray(v)?v.filter(x=>(x.name||'').startsWith('CLI-QA-S03')||(x.title||'').startsWith('CLI-QA-S03')):k==='strategy_inputs'?v.filter(x=>x.id!=='text'):k==='trades'&&Array.isArray(v)?{length:v.length,first:v[0],last:v.at(-1)}:k==='entries'&&Array.isArray(v)?{length:v.length,first:v[0],last:v.at(-1)}:v));
console.log(JSON.stringify({tag,status:r.status,duration_ms:record.duration_ms,json:safe,stderr:r.stderr}));
const expectedExit=tag==='091-error-compile'||tag==='092-error-diagnostics'?1:0;
if(r.status!==expectedExit)throw Error('Unexpected exit: '+r.status+' expected '+expectedExit);
if(!json)throw Error('Missing JSON response');
if(expectedExit===0&&json.success!==true)throw Error('Unsuccessful JSON');
if(['compile','raw-compile'].includes(args[1])&&expectedExit===0&&(!json.compiled||!json.report_ready||json.strategy_id!=='IC4e6I'))throw Error('Compile identity/report mismatch');
if(args[1]==='open'&&json.script_id!==postId)throw Error('Open document mismatch');
if(args[1]==='save'&&json.script_id!==preId)throw Error('Saved document mismatch');
if(args[0]==='data'&&['strategy','ledger','trades'].includes(args[1])&&json.strategy_id!=='IC4e6I')throw Error('Data study mismatch');
if(args[0]==='state'&&(json.studies?.filter(s=>s.name==='CLI-QA-S03-EMA').length!==1||!json.studies.some(s=>s.id==='IC4e6I')))throw Error('State study count mismatch');
if(tag==='092-error-diagnostics'&&(!json.has_errors||!json.errors?.some(e=>e.message.includes('math.qa_missing'))))throw Error('Expected injected diagnostic missing');
checkFence('-post',postId);
