import { register } from '../router.js';
import { runDeep,deepStatus,waitDeep,deepResults,resetNormal } from '../../core/deep-backtest.js';
register('backtest',{description:'Explicit native Deep runs, finite observation and immutable result pages; chart reports never substitute for Deep',subcommands:new Map([
  ['run',{description:'Dispatch a Deep request for an exact verified strategy/source/settings and explicit UTC-offset period',options:{mode:{type:'string',description:'Required deep; normal collection remains data strategy'},from:{type:'string',description:'Explicit-offset ISO timestamp normalizing to UTC midnight; whole UTC days only'},to:{type:'string',description:'Explicit-offset ISO timestamp normalizing to UTC midnight; whole UTC days only'},timezone:{type:'string',description:'Native calculation UTC or Etc/UTC only (default UTC); other zones fail before dispatch'},'request-id':{type:'string',description:'Stable caller request ID; unknown outcomes are not resent'},'strategy-id':{type:'string',description:'Exact current owned strategy ID'}},handler:opts=>{if(opts.mode!=='deep')throw Object.assign(new Error('backtest run requires --mode deep.'),{code:'INVALID_DEEP_REQUEST'});return runDeep({from:opts.from,to:opts.to,timezone:opts.timezone,request_id:opts['request-id'],strategy_id:opts['strategy-id']});}}],
  ['status',{description:'Pure observation of the exact native run; no panel mount, date change or calculation dispatch',options:{'run-id':{type:'string',description:'Exact run ID from accepted response'}},handler:opts=>deepStatus({run_id:opts['run-id']})}],
  ['wait',{description:'Wait finitely for the exact native run; timeout does not cancel',options:{'run-id':{type:'string',description:'Exact run ID'},timeout:{type:'string',description:'Milliseconds (default 30000, max 300000)'}},handler:opts=>waitDeep({run_id:opts['run-id'],timeout:Number(opts.timeout||30000)})}],
  ['results',{description:'Verified Deep metrics and finite ledger page from the same immutable native snapshot/revision',options:{'run-id':{type:'string',description:'Exact run ID'},offset:{type:'string',description:'First trade ordinal (default 0)'},limit:{type:'string',description:'Page size 1..500 (default 100)'},'report-revision':{type:'string',description:'Revision from first page; changed reports fail'}},handler:opts=>deepResults({run_id:opts['run-id'],offset:Number(opts.offset||0),limit:Number(opts.limit||100),report_revision:opts['report-revision']})}],
  ['normal',{description:'Explicitly reset to chart session after native Deep settlement; no silent cancellation',handler:()=>resetNormal()}],
])});


